openapi: 3.1.0
info:
  title: CamundaServicesAPI
  description: API documentation for Camunda workflow services
  contact:
    name: Rahma Hassan
    email: rahma.hassan@qeema.net
  version: 1.0.0
servers:
 -
  url: https://devcamunda-upsource.apps.qeema.io
  description: Generated server url
security:
 -
  default: []
paths:
  /api/v1/tasks/{taskId}:
    put:
      tags:
       - Tasks
      summary: Update a task
      operationId: updateTask
      parameters:
       -
        name: X-Correlation-ID
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
       -
        name: taskId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: 496d5697-b02b-11f0-94aa-f20fb8ac22b1
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TaskDto"
            example:
              name: Review Marketing Campaign
              description: Review the Q4 campaign content and provide final approval before publishing.
              assignee: ahmeddeeb11111@gmail.com
              due: 2025-10-31T22:30:00.000+0300
        required: true
      responses:
        "200":
          description: Operation completed successfully
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResponseVoid"
              examples:
                BackendSuccess:
                  $ref: "#/components/examples/ApiResponseVoid"
                BackendFailure:
                  $ref: "#/components/examples/TaskNotFoundError"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "429":
          $ref: "#/components/responses/TooManyRequests"
        "500":
          $ref: "#/components/responses/InternalServerError"
        "503":
          $ref: "#/components/responses/ServiceUnavailable"
      security:
       -
        default:
         - camunda:access
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - oauth2
        optional: false
  /api/v1/process-instances/{processInstanceId}/suspended:
    put:
      tags:
       - Process Instances
      summary: Activate or suspend a running process instance
      operationId: activateSuspendProcessInstance
      parameters:
       -
        name: X-Correlation-ID
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
       -
        name: processInstanceId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: 6e983370-ae45-11f0-b428-1688b2a2c28a
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ActivateSuspendRequestDto"
            example:
              suspended: true
        required: true
      responses:
        "200":
          description: Operation completed successfully
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResponseVoid"
              examples:
                BackendSuccess:
                  $ref: "#/components/examples/ApiResponseVoid"
                BackendFailure:
                  $ref: "#/components/examples/MissingRequestBodyError"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "429":
          $ref: "#/components/responses/TooManyRequests"
        "500":
          $ref: "#/components/responses/InternalServerError"
        "503":
          $ref: "#/components/responses/ServiceUnavailable"
      security:
       -
        default:
         - camunda:access
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - oauth2
        optional: false
  /api/v1/definitions/processes/{processKey}/tasks/{taskKey}:
    get:
      tags:
       - Definitions
      summary: Get a task definition
      operationId: getTaskDefinition
      parameters:
       -
        name: X-Correlation-ID
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
       -
        name: processKey
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: announcementProcess
       -
        name: taskKey
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: UserTask_ReviewByMarketingManager
      responses:
        "200":
          description: Operation completed successfully
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResponseTaskDefinitionDto"
              examples:
                BackendSuccess:
                  $ref: "#/components/examples/TaskDefinitionSuccess"
                BackendFailure:
                  $ref: "#/components/examples/TaskDefinitionNotFoundError"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "429":
          $ref: "#/components/responses/TooManyRequests"
        "500":
          $ref: "#/components/responses/InternalServerError"
        "503":
          $ref: "#/components/responses/ServiceUnavailable"
      security:
       -
        default:
         - camunda:access
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - oauth2
        optional: false
    put:
      tags:
       - Definitions
      summary: Update a task definition
      operationId: updateTaskDefinition
      parameters:
       -
        name: X-Correlation-ID
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
       -
        name: processKey
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: announcementProcess
       -
        name: taskKey
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: UserTask_ReviewByMarketingManager
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TaskDefinitionDto"
            example:
              slaDays: 3
              inputs:
               -
                label: Approve/Reject Request
                description: Decision on the request
                type: Radio button
                options:
                 - Approve
                 - Reject
               -
                label: Comment
                description: Additional remarks or feedback
                type: Multi-line text
                options:
                 - Free text
               -
                label: Attachments
                description: Supporting files
                type: File upload
                options:
                 - PDF
                 - JPG
                 - PNG
                 - DOCX
        required: true
      responses:
        "200":
          description: Operation completed successfully
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResponseTaskDefinitionDto"
              examples:
                BackendSuccess:
                  $ref: "#/components/examples/TaskDefinitionSuccess"
                BackendFailure:
                  $ref: "#/components/examples/TaskDefinitionNotFoundError"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "429":
          $ref: "#/components/responses/TooManyRequests"
        "500":
          $ref: "#/components/responses/InternalServerError"
        "503":
          $ref: "#/components/responses/ServiceUnavailable"
      security:
       -
        default:
         - camunda:access
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - oauth2
        optional: false
  /api/v1/tasks/{taskId}/complete:
    post:
      tags:
       - Tasks
      summary: Complete a task
      operationId: completeTask
      parameters:
       -
        name: X-Correlation-ID
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
       -
        name: taskId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: 0f4fa27a-ae4c-11f0-b428-1688b2a2c28a
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CompleteTaskRequestDto"
            example:
              variables:
                lineManagerResponse:
                  value: "yes"
                comment:
                  value: Good Request! ü§ù
        required: true
      responses:
        "200":
          description: Operation completed successfully
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResponseVoid"
              examples:
                BackendSuccess:
                  $ref: "#/components/examples/ApiResponseVoid"
                BackendFailure:
                  $ref: "#/components/examples/CompleteTaskInternalServerError"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "429":
          $ref: "#/components/responses/TooManyRequests"
        "500":
          $ref: "#/components/responses/InternalServerError"
        "503":
          $ref: "#/components/responses/ServiceUnavailable"
      security:
       -
        default:
         - camunda:access
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - oauth2
        optional: false
  /api/v1/process-instances:
    get:
      tags:
       - Process Instances
      summary: Get process instances
      operationId: getProcessInstances
      parameters:
       -
        name: X-Correlation-ID
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
       -
        name: processDefinitionKey
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
        example: announcementProcess
      responses:
        "200":
          description: Operation completed successfully
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResponseListHistoricProcessInstanceDto"
              examples:
                BackendSuccess:
                  $ref: "#/components/examples/GetHistoricProcessInstancesSuccess"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "429":
          $ref: "#/components/responses/TooManyRequests"
        "500":
          $ref: "#/components/responses/InternalServerError"
        "503":
          $ref: "#/components/responses/ServiceUnavailable"
      security:
       -
        default:
         - camunda:access
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - oauth2
        optional: false
    post:
      tags:
       - Process Instances
      summary: Start a new process instance
      operationId: startProcessInstance
      parameters:
       -
        name: X-Correlation-ID
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
       -
        name: processDefinitionKey
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
        example: announcementProcess
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StartProcessInstanceRequestDto"
            example:
              businessKey: req-1
              variables:
                requesterEmail:
                  value: ahmeddeeb22222@gmail.com
                  type: String
                type:
                  value: "[\"Internal\", \"Public\"]"
                  type: Object
                  valueInfo:
                    objectTypeName: java.util.ArrayList
                    serializationDataFormat: application/json
        required: true
      responses:
        "200":
          description: Operation completed successfully
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResponseProcessInstanceDto"
              examples:
                BackendSuccess:
                  $ref: "#/components/examples/StartProcessInstanceSuccess"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "429":
          $ref: "#/components/responses/TooManyRequests"
        "500":
          $ref: "#/components/responses/InternalServerError"
        "503":
          $ref: "#/components/responses/ServiceUnavailable"
      security:
       -
        default:
         - camunda:access
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - oauth2
        optional: false
  /api/v1/tasks:
    get:
      tags:
       - Tasks
      summary: Get tasks
      operationId: getTasks
      parameters:
       -
        name: X-Correlation-ID
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
       -
        name: processDefinitionKey
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
        example: announcementProcess
       -
        name: processInstanceId
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
       -
        name: assignee
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
       -
        name: dueDate
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
       -
        name: dueAfter
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
       -
        name: dueBefore
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
       -
        name: createdOn
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
       -
        name: createdAfter
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
       -
        name: createdBefore
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
       -
        name: sortBy
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
       -
        name: sortOrder
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
       -
        name: firstResult
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int32
       -
        name: maxResults
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: Operation completed successfully
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResponseListTaskDto"
              examples:
                BackendSuccess:
                  $ref: "#/components/examples/GetTasksSuccess"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "429":
          $ref: "#/components/responses/TooManyRequests"
        "500":
          $ref: "#/components/responses/InternalServerError"
        "503":
          $ref: "#/components/responses/ServiceUnavailable"
      security:
       -
        default:
         - camunda:access
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - oauth2
        optional: false
  /api/v1/process-instances/{processInstanceId}:
    get:
      tags:
       - Process Instances
      summary: Get a process instance details (steps and variables)
      operationId: getProcessInstanceDetails
      parameters:
       -
        name: X-Correlation-ID
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
       -
        name: processInstanceId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: 6e983370-ae45-11f0-b428-1688b2a2c28a
      responses:
        "200":
          description: Operation completed successfully
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResponseProcessInstanceDetailsDto"
              examples:
                BackendSuccess:
                  $ref: "#/components/examples/GetHistoricDataSuccess"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "429":
          $ref: "#/components/responses/TooManyRequests"
        "500":
          $ref: "#/components/responses/InternalServerError"
        "503":
          $ref: "#/components/responses/ServiceUnavailable"
      security:
       -
        default:
         - camunda:access
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - oauth2
        optional: false
    delete:
      tags:
       - Process Instances
      summary: Cancel a running process instance
      operationId: deleteProcessInstance
      parameters:
       -
        name: X-Correlation-ID
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
       -
        name: processInstanceId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: 6e983370-ae45-11f0-b428-1688b2a2c28a
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeleteProcessInstanceRequestDto"
            example:
              deleteReason: This is an invalid request...
        required: true
      responses:
        "200":
          description: Operation completed successfully
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResponseVoid"
              examples:
                BackendSuccess:
                  $ref: "#/components/examples/ApiResponseVoid"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "429":
          $ref: "#/components/responses/TooManyRequests"
        "500":
          $ref: "#/components/responses/InternalServerError"
        "503":
          $ref: "#/components/responses/ServiceUnavailable"
      security:
       -
        default:
         - camunda:access
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - oauth2
        optional: false
  /api/v1/definitions/processes/{processKey}:
    get:
      tags:
       - Definitions
      summary: Get a process definition
      operationId: getProcessDefinition
      parameters:
       -
        name: X-Correlation-ID
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
       -
        name: processKey
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: announcementProcess
      responses:
        "200":
          description: Operation completed successfully
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResponseProcessDefinitionDto"
              examples:
                BackendSuccess:
                  $ref: "#/components/examples/GetProcessDefinitionSuccess"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "429":
          $ref: "#/components/responses/TooManyRequests"
        "500":
          $ref: "#/components/responses/InternalServerError"
        "503":
          $ref: "#/components/responses/ServiceUnavailable"
      security:
       -
        default:
         - camunda:access
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - oauth2
        optional: false
components:
  schemas:
    CamundaFormRef:
      type: object
      properties:
        key:
          type: string
        binding:
          type: string
        version:
          type: integer
          format: int32
    TaskDto:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        assignee:
          type: string
        created:
          type: string
        due:
          type: string
        followUp:
          type:
           - string
           - "null"
        lastUpdated:
          type:
           - string
           - "null"
        delegationState:
          type:
           - string
           - "null"
        description:
          type:
           - string
           - "null"
        executionId:
          type: string
        owner:
          type:
           - string
           - "null"
        parentTaskId:
          type:
           - string
           - "null"
        priority:
          type: integer
          format: int32
        processDefinitionId:
          type: string
        processInstanceId:
          type: string
        taskDefinitionKey:
          type: string
        caseExecutionId:
          type:
           - string
           - "null"
        caseInstanceId:
          type:
           - string
           - "null"
        caseDefinitionId:
          type:
           - string
           - "null"
        suspended:
          type: boolean
        formKey:
          type:
           - string
           - "null"
        camundaFormRef:
          anyOf:
           -
            type: "null"
           -
            $ref: "#/components/schemas/CamundaFormRef"
        tenantId:
          type:
           - string
           - "null"
        taskState:
          type: string
    ApiResponseVoid:
      type: object
      properties:
        header:
          $ref: "#/components/schemas/Header"
        data: {}
    Header:
      type: object
      properties:
        X-Correlation-ID:
          type: string
        timestamp:
          type: string
          format: date-time
        status:
          type: string
        code:
          type: string
        message:
          type: string
    ActivateSuspendRequestDto:
      type: object
      properties:
        suspended:
          type: boolean
    InputDto:
      type: object
      properties:
        label:
          type: string
        description:
          type: string
        type:
          type: string
        options:
          type: array
          items:
            type: string
      required:
       - description
       - label
       - options
       - type
    TaskDefinitionDto:
      type: object
      properties:
        slaDays:
          type: integer
          format: int32
        inputs:
          type: array
          items:
            $ref: "#/components/schemas/InputDto"
    ApiResponseTaskDefinitionDto:
      type: object
      properties:
        header:
          $ref: "#/components/schemas/Header"
        data:
          anyOf:
           -
            type: "null"
           -
            $ref: "#/components/schemas/TaskDefinitionDto"
    CompleteTaskRequestDto:
      type: object
      properties:
        variables:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/ProcessVariableDto"
    ProcessVariableDto:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
        value: {}
        valueInfo:
          type: object
          additionalProperties: {}
      required:
       - value
    StartProcessInstanceRequestDto:
      type: object
      properties:
        variables:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/ProcessVariableDto"
        businessKey:
          type: string
    ApiResponseProcessInstanceDto:
      type: object
      properties:
        header:
          $ref: "#/components/schemas/Header"
        data:
          $ref: "#/components/schemas/ProcessInstanceDto"
    Link:
      type: object
      properties:
        method:
          type: string
        href:
          type: string
        rel:
          type: string
    ProcessInstanceDto:
      type: object
      properties:
        links:
          type: array
          items:
            $ref: "#/components/schemas/Link"
        id:
          type: string
        definitionId:
          type: string
        businessKey:
          type: string
        caseInstanceId:
          type:
           - string
           - "null"
        ended:
          type: boolean
        suspended:
          type: boolean
        tenantId:
          type:
           - string
           - "null"
        definitionKey:
          type: string
    ApiResponseListTaskDto:
      type: object
      properties:
        header:
          $ref: "#/components/schemas/Header"
        data:
          type: array
          items:
            $ref: "#/components/schemas/TaskDto"
    ApiResponseListHistoricProcessInstanceDto:
      type: object
      properties:
        header:
          $ref: "#/components/schemas/Header"
        data:
          type: array
          items:
            $ref: "#/components/schemas/HistoricProcessInstanceDto"
    HistoricProcessInstanceDto:
      type: object
      properties:
        id:
          type: string
        businessKey:
          type:
           - string
           - "null"
        processDefinitionId:
          type: string
        processDefinitionKey:
          type: string
        processDefinitionName:
          type:
           - string
           - "null"
        processDefinitionVersion:
          type: integer
          format: int32
        startTime:
          type: string
          format: date-time
        endTime:
          type:
           - string
           - "null"
          format: date-time
        removalTime:
          type:
           - string
           - "null"
          format: date-time
        durationInMillis:
          type:
           - string
           - "null"
          format: int64
        startUserId:
          type:
           - string
           - "null"
        startActivityId:
          type: string
        deleteReason:
          type:
           - string
           - "null"
        rootProcessInstanceId:
          type: string
        superProcessInstanceId:
          type:
           - string
           - "null"
        superCaseInstanceId:
          type:
           - string
           - "null"
        caseInstanceId:
          type:
           - string
           - "null"
        tenantId:
          type:
           - string
           - "null"
        state:
          type: string
        restartedProcessInstanceId:
          type:
           - string
           - "null"
    ApiResponseProcessInstanceDetailsDto:
      type: object
      properties:
        header:
          $ref: "#/components/schemas/Header"
        data:
          $ref: "#/components/schemas/ProcessInstanceDetailsDto"
    HistoricActivityInstanceDto:
      type: object
      properties:
        id:
          type: string
        parentActivityInstanceId:
          type: string
        activityId:
          type: string
        activityName:
          type: string
        activityType:
          type: string
        processDefinitionKey:
          type: string
        processDefinitionId:
          type: string
        processInstanceId:
          type: string
        executionId:
          type: string
        taskId:
          type:
           - string
           - "null"
        calledProcessInstanceId:
          type:
           - string
           - "null"
        calledCaseInstanceId:
          type:
           - string
           - "null"
        assignee:
          type:
           - string
           - "null"
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
        durationInMillis:
          type: integer
          format: int64
        canceled:
          type: boolean
        completeScope:
          type: boolean
        tenantId:
          type:
           - string
           - "null"
        removalTime:
          type:
           - string
           - "null"
          format: date-time
        rootProcessInstanceId:
          type: string
    ProcessInstanceDetailsDto:
      type: object
      properties:
        historicActivityInstances:
          type: array
          items:
            $ref: "#/components/schemas/HistoricActivityInstanceDto"
        processVariables:
          type: array
          items:
            $ref: "#/components/schemas/ProcessVariableDto"
    ApiResponseProcessDefinitionDto:
      type: object
      properties:
        header:
          $ref: "#/components/schemas/Header"
        data:
          $ref: "#/components/schemas/ProcessDefinitionDto"
    ProcessDefinitionDto:
      type: object
      properties:
        key:
          type: string
        tasks:
          type: array
          items:
            type: string
        inputs:
          type: array
          items:
            $ref: "#/components/schemas/InputDto"
    DeleteProcessInstanceRequestDto:
      type: object
      properties:
        deleteReason:
          type: string
    Error:
      type: object
      properties:
        code:
          type: string
          description: WSO2 error code
          enum:
           - "900900"
           - "900901"
           - "900902"
           - "900905"
           - "900907"
           - "900909"
           - "900911"
           - "900906"
           - "900908"
           - "900910"
           - "900422"
           - "900800"
           - "900802"
           - "900803"
           - "900804"
           - "900805"
           - "900806"
           - "900807"
           - "700700"
           - "900801"
        message:
          type: string
          description: Error message
        description:
          type: string
          description: Detailed error description
      required:
       - code
       - description
       - message
  responses:
    Unauthorized:
      description: Unauthorized - Authentication credentials are missing or invalid
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          examples:
            invalidCredentials:
              $ref: "#/components/examples/InvalidCredentials"
    Forbidden:
      description: Forbidden - The client does not have access rights to the content
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          examples:
            insufficientScope:
              $ref: "#/components/examples/InsufficientScope"
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          examples:
            unclassifiedAuthFailure:
              summary: Unclassified authentication failure
              value:
                code: "900900"
                message: Unclassified authentication failure
                description: ' Backend service for key validation is not accessible when trying to invoke an API.'
    ServiceUnavailable:
      description: Service Unavailable - The server is unable to handle the request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          examples:
            apiBlocked:
              $ref: "#/components/examples/ApiBlocked"
    TooManyRequests:
      description: Too Many Requests - Rate limit exceeded
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
  examples:
    InvalidCredentials:
      summary: Invalid Credentials
      value:
        code: "900901"
        message: Invalid Credentials
        description: Invalid Credentials. Make sure you have provided the correct security credentials
    InsufficientScope:
      summary: Scope validation failed
      value:
        code: "900910"
        message: The access token does not allow you to access the requested resource
        description: "Access failure for API: /api/1.0.0, version: 1.0.0 status: (900910) - The access token does not allow you to access the requested resource"
    ApiBlocked:
      summary: API blocked
      value:
        code: "700700"
        message: API blocked
        description: This API has been blocked temporarily. Please try again later or contact the system administrators.
    ApiResponseVoid:
      value:
        header:
          X-Correlation-ID: bb2b206d-15a8-40c3-b856-c2e07d93727b
          timestamp: 2025-10-16T11:00:00.567890100Z
          status: SUCCESS
          code: "0000"
          message: Operation completed successfully
        data: null
    TaskNotFoundError:
      value:
        header:
          X-Correlation-ID: ab2c206d-15a8-40c3-b856-c2e07d93727b
          timestamp: 2025-10-23T16:17:19.843765100Z
          status: FAILURE
          code: "404"
          message: "404 : \"{\"type\":\"InvalidRequestException\",\"message\":\"No matching task with id 496d5697-b02b-\",\"code\":null}\""
        data: null
    MissingRequestBodyError:
      value:
        header:
          X-Correlation-ID: "1"
          timestamp: 2025-10-23T16:00:26.206908700Z
          status: FAILURE
          code: "400"
          message: "Required request body is missing: public org.springframework.http.ResponseEntity<com.qeema.camunda.controller.api.ApiResponse<java.lang.Void>> com.qeema.camunda.controller.ProcessInstanceController.activateSuspendProcessInstance(java.lang.String,java.lang.String,java.util.Map<java.lang.String, java.lang.Boolean>)"
        data: null
    TaskDefinitionSuccess:
      value:
        header:
          X-Correlation-ID: "1"
          timestamp: 2025-10-23T16:21:29.743673200Z
          status: SUCCESS
          code: "0000"
          message: Operation completed successfully
        data:
          slaDays: 3
          inputs:
           -
            label: Approve/Reject Request
            description: Decision on the request
            type: Radio button
            options:
             - Reject
             - Approve
           -
            label: Comment
            description: Additional remarks or feedback
            type: Multi-line text
            options:
             - Free text
           -
            label: Attachments
            description: Supporting files
            type: File upload
            options:
             - DOCX
             - JPG
             - PDF
             - PNG
    TaskDefinitionNotFoundError:
      value:
        header:
          X-Correlation-ID: "1"
          timestamp: 2025-10-23T16:22:12.128676Z
          status: FAILURE
          code: "404"
          message: Task definition with key 'lskdjflksjdklfdsk' in process 'announcementProcess' not found
        data: null
    CompleteTaskInternalServerError:
      value:
        header:
          X-Correlation-ID: "1"
          timestamp: 2025-10-23T16:14:22.032069900Z
          status: FAILURE
          code: "500"
          message: "500 : \"{\"type\":\"RestException\",\"message\":\"Cannot complete task 275745fc-b018-11f0-94aa-f20fb8ac22b1: Cannot find task with id 275745fc-b018-11f0-94aa-f20fb8ac22b1: task is null\",\"code\":0}\""
        data: null
    GetHistoricProcessInstancesSuccess:
      value:
        header:
          X-Correlation-ID: "1"
          timestamp: 2025-10-23T15:56:37.515453900Z
          status: SUCCESS
          code: "0000"
          message: Operation completed successfully
        data:
         -
          id: 1546e146-b00f-11f0-b428-1688b2a2c28a
          businessKey: null
          processDefinitionId: announcementProcess:7:1327f8d6-b00f-11f0-b428-1688b2a2c28a
          processDefinitionKey: announcementProcess
          processDefinitionName: null
          processDefinitionVersion: 7
          startTime: 2025-10-23T12:52:07.645Z
          endTime: null
          removalTime: null
          durationInMillis: null
          startUserId: null
          startActivityId: Event_FormSubmitted
          deleteReason: null
          rootProcessInstanceId: 1546e146-b00f-11f0-b428-1688b2a2c28a
          superProcessInstanceId: null
          superCaseInstanceId: null
          caseInstanceId: null
          tenantId: null
          state: ACTIVE
          restartedProcessInstanceId: null
         -
          id: 82b18398-b027-11f0-94aa-f20fb8ac22b1
          businessKey: req-1
          processDefinitionId: announcementProcess:8:a8f91dee-b017-11f0-94aa-f20fb8ac22b1
          processDefinitionKey: announcementProcess
          processDefinitionName: null
          processDefinitionVersion: 8
          startTime: 2025-10-23T15:46:59.138Z
          endTime: null
          removalTime: null
          durationInMillis: null
          startUserId: null
          startActivityId: Event_FormSubmitted
          deleteReason: null
          rootProcessInstanceId: 82b18398-b027-11f0-94aa-f20fb8ac22b1
          superProcessInstanceId: null
          superCaseInstanceId: null
          caseInstanceId: null
          tenantId: null
          state: ACTIVE
          restartedProcessInstanceId: null
    GetHistoricDataSuccess:
      value:
        header:
          X-Correlation-ID: "1"
          timestamp: 2025-10-23T15:57:34.926813600Z
          status: SUCCESS
          code: "0000"
          message: Operation completed successfully
        data:
          historicActivityInstances:
           -
            id: bd694aa5-b028-11f0-94aa-f20fb8ac22b1
            parentActivityInstanceId: SubProcess_Initializing:bd692492-b028-11f0-94aa-f20fb8ac22b1
            activityId: ServiceTask_SetTasksDefinitionVariables
            activityName: Set tasks definition variables
            activityType: serviceTask
            processDefinitionKey: announcementProcess
            processDefinitionId: announcementProcess:8:a8f91dee-b017-11f0-94aa-f20fb8ac22b1
            processInstanceId: bd67c4dc-b028-11f0-94aa-f20fb8ac22b1
            executionId: bd694aa4-b028-11f0-94aa-f20fb8ac22b1
            taskId: null
            calledProcessInstanceId: null
            calledCaseInstanceId: null
            assignee: null
            startTime: 2025-10-23T15:55:47.146Z
            endTime: 2025-10-23T15:55:48.215Z
            durationInMillis: 1069
            canceled: false
            completeScope: false
            tenantId: null
            removalTime: null
            rootProcessInstanceId: bd67c4dc-b028-11f0-94aa-f20fb8ac22b1
          processVariables:
           -
            type: String
            value: ahmeddeeb22222@gmail.com
            valueInfo:
              objectTypeName: null
              serializationDataFormat: null
            id: bd6812fd-b028-11f0-94aa-f20fb8ac22b1
            name: requesterEmail
            processDefinitionKey: announcementProcess
            processDefinitionId: announcementProcess:8:a8f91dee-b017-11f0-94aa-f20fb8ac22b1
            processInstanceId: bd67c4dc-b028-11f0-94aa-f20fb8ac22b1
            executionId: bd67c4dc-b028-11f0-94aa-f20fb8ac22b1
            activityInstanceId: bd67c4dc-b028-11f0-94aa-f20fb8ac22b1
            caseDefinitionKey: null
            caseDefinitionId: null
            caseInstanceId: null
            caseExecutionId: null
            taskId: null
            errorMessage: null
            tenantId: null
            state: CREATED
            createTime: 2025-10-23T15:55:47.138Z
            removalTime: null
            rootProcessInstanceId: bd67c4dc-b028-11f0-94aa-f20fb8ac22b1
           -
            type: Object
            value:
             - announcement-banner.png
             - supporting-image.jpg
            valueInfo:
              objectTypeName: java.util.ArrayList
              serializationDataFormat: application/json
            id: bd686125-b028-11f0-94aa-f20fb8ac22b1
            name: attachments
            processDefinitionKey: announcementProcess
            processDefinitionId: announcementProcess:8:a8f91dee-b017-11f0-94aa-f20fb8ac22b1
            processInstanceId: bd67c4dc-b028-11f0-94aa-f20fb8ac22b1
            executionId: bd67c4dc-b028-11f0-94aa-f20fb8ac22b1
            activityInstanceId: bd67c4dc-b028-11f0-94aa-f20fb8ac22b1
            caseDefinitionKey: null
            caseDefinitionId: null
            caseInstanceId: null
            caseExecutionId: null
            taskId: null
            errorMessage: null
            tenantId: null
            state: CREATED
            createTime: 2025-10-23T15:55:47.14Z
            removalTime: null
            rootProcessInstanceId: bd67c4dc-b028-11f0-94aa-f20fb8ac22b1
    StartProcessInstanceSuccess:
      value:
        header:
          X-Correlation-ID: "1"
          timestamp: 2025-10-23T15:55:47.764545300Z
          status: SUCCESS
          code: "0000"
          message: Operation completed successfully
        data:
          links:
           -
            method: GET
            href: https://devcamunda.apps.qeema.io/engine-rest/process-instance/bd67c4dc-b028-11f0-94aa-f20fb8ac22b1
            rel: self
          id: bd67c4dc-b028-11f0-94aa-f20fb8ac22b1
          definitionId: announcementProcess:8:a8f91dee-b017-11f0-94aa-f20fb8ac22b1
          businessKey: req-1
          caseInstanceId: null
          ended: false
          suspended: false
          tenantId: null
          definitionKey: announcementProcess
    GetTasksSuccess:
      value:
        header:
          X-Correlation-ID: "1"
          timestamp: 2025-10-23T16:11:20.351952Z
          status: SUCCESS
          code: "0000"
          message: Operation completed successfully
        data:
         -
          id: 275745fc-b018-11f0-94aa-f20fb8ac22b1
          name: Review by Nawaf Abdulaziz Aldhubaib
          assignee: ahmeddeeb22222@gmail.com
          created: 2025-10-23T13:57:03.422Z
          due: 2025-10-25T13:57:03.437Z
          followUp: null
          lastUpdated: null
          delegationState: null
          description: null
          executionId: 2741e935-b018-11f0-94aa-f20fb8ac22b1
          owner: null
          parentTaskId: null
          priority: 50
          processDefinitionId: announcementProcess:8:a8f91dee-b017-11f0-94aa-f20fb8ac22b1
          processInstanceId: ce57eb8e-b017-11f0-94aa-f20fb8ac22b1
          taskDefinitionKey: UserTask_ReviewByLineManager
          caseExecutionId: null
          caseInstanceId: null
          caseDefinitionId: null
          suspended: false
          formKey: null
          camundaFormRef: null
          tenantId: null
          taskState: Created
    GetProcessDefinitionSuccess:
      value:
        header:
          X-Correlation-ID: "1"
          timestamp: 2025-10-23T16:18:01.200210200Z
          status: SUCCESS
          code: "0000"
          message: Operation completed successfully
        data:
          key: announcementProcess
          tasks:
           - UserTask_EditRequest
           - UserTask_PrepareDraft
           - UserTask_ReviewByDirector
           - UserTask_ReviewByLineManager
           - UserTask_ReviewByMarketingManager
           - UserTask_ReviewByRequester
           - UserTask_SetDueDate
           - UserTask_SubmitInfo
          inputs:
           -
            label: Type
            description: Type of announcement
            type: Checkbox list
            options:
             - Internal
             - Public
           -
            label: Audience
            description: Target audience
            type: Checkbox list
            options:
             - Corporate Employees
             - CSM Employees
             - All Employees
           -
            label: Location(s)
            description: Announcement locations
            type: Multi-select drop-down
            options:
             - Queen Noura University
             - Qassim
             - Medina
             - Alaqarya 3th floor
           -
            label: Channels
            description: Publication channels
            type: Checkbox list
            options:
             - LinkedIn
             - Rahaba
             - Twasol
             - Rahaba+
             - Twitter
             - Snapchat
           -
            label: Description / Brief
            description: Announcement summary
            type: Multi-line text
            options:
             - Free text
           -
            label: Attachments
            description: Supporting files
            type: File upload
            options:
             - JPG
             - DOCX
             - PDF
             - PNG
           -
            label: Proposed Timeline
            description: Suggested publishing date
            type: Date picker
            options:
             - Calendar field
           -
            label: Title
            description: Announcement request title
            type: Text
            options:
             - Free text
  securitySchemes:
    default:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://test.com
          scopes:
            camunda:access: access scope for camunda APIs
          x-scopes-bindings:
            camunda:access: ""
        authorizationCode:
          authorizationUrl: https://wso2is.apps.qeema.io/oauth2/authorize
          tokenUrl: https://wso2is.apps.qeema.io/oauth2/token
          scopes: {}
x-wso2-api-key-header: ApiKey
x-wso2-auth-header: Authorization
x-wso2-cors:
  corsConfigurationEnabled: false
  accessControlAllowOrigins:
   - '*'
  accessControlAllowCredentials: false
  accessControlAllowHeaders:
   - authorization
   - Access-Control-Allow-Origin
   - Content-Type
   - SOAPAction
   - apikey
   - Internal-Key
  accessControlAllowMethods:
   - GET
   - PUT
   - POST
   - DELETE
   - PATCH
   - OPTIONS
x-wso2-production-endpoints:
  urls:
   - https://devcamunda-upsource.apps.qeema.io
  type: http
x-wso2-sandbox-endpoints:
  urls:
   - https://devcamunda-upsource.apps.qeema.io
  type: http
x-wso2-basePath: /camundaservicesapi/1.0.0
x-wso2-transports:
 - http
 - https
x-wso2-application-security:
  security-types:
   - oauth2
  optional: false
x-wso2-response-cache:
  enabled: false
  cacheTimeoutInSeconds: 300
